paths:
  /postSecondarySchools:
    post:
      tags:
        - postSecondarySchool
      summary: Create a new instance of the model and persist it into the data source.
      operationId: postSecondarySchool.create
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            $ref: '#/definitions/postSecondarySchool'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/postSecondarySchool'
      deprecated: false
    put:
      tags:
        - postSecondarySchool
      summary: Update an existing model instance or insert a new one into the data source.
      operationId: postSecondarySchool.upsert
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            $ref: '#/definitions/postSecondarySchool'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/postSecondarySchool'
      deprecated: false
    get:
      tags:
        - postSecondarySchool
      summary: Find all instances of the model matched by filter from the data source.
      operationId: postSecondarySchool.find
      parameters:
        - name: filter
          in: query
          description: 'Filter defining fields, where, include, order, offset, and limit'
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: array
            items:
              $ref: '#/definitions/postSecondarySchool'
      deprecated: false
  '/postSecondarySchools/{id}/exists':
    get:
      tags:
        - postSecondarySchool
      summary: Check whether a model instance exists in the data source.
      operationId: 'postSecondarySchool.exists__get_postSecondarySchools_{id}_exists'
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              exists:
                type: boolean
      deprecated: false
  '/postSecondarySchools/{id}':
    head:
      tags:
        - postSecondarySchool
      summary: Check whether a model instance exists in the data source.
      operationId: 'postSecondarySchool.exists__head_postSecondarySchools_{id}'
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              exists:
                type: boolean
      deprecated: false
    get:
      tags:
        - postSecondarySchool
      summary: Find a model instance by id from the data source.
      operationId: postSecondarySchool.findById
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
        - name: filter
          in: query
          description: Filter defining fields and include
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/postSecondarySchool'
      deprecated: false
    delete:
      tags:
        - postSecondarySchool
      summary: Delete a model instance by id from the data source.
      operationId: postSecondarySchool.deleteById
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
      deprecated: false
    put:
      tags:
        - postSecondarySchool
      summary: Update attributes for a model instance and persist it into the data source.
      operationId: postSecondarySchool.prototype.updateAttributes
      parameters:
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            $ref: '#/definitions/postSecondarySchool'
        - name: id
          in: path
          description: PersistedModel id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/postSecondarySchool'
      deprecated: false
  /postSecondarySchools/findOne:
    get:
      tags:
        - postSecondarySchool
      summary: Find first instance of the model matched by filter from the data source.
      operationId: postSecondarySchool.findOne
      parameters:
        - name: filter
          in: query
          description: 'Filter defining fields, where, include, order, offset, and limit'
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/postSecondarySchool'
      deprecated: false
  /postSecondarySchools/update:
    post:
      tags:
        - postSecondarySchool
      summary: Update instances of the model matched by where from the data source.
      operationId: postSecondarySchool.updateAll
      parameters:
        - name: where
          in: query
          description: Criteria to match model instances
          required: false
          type: string
          format: JSON
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            $ref: '#/definitions/postSecondarySchool'
      responses:
        '200':
          description: Request was successful
          schema:
            description: The number of instances updated
            type: object
      deprecated: false
  /postSecondarySchools/count:
    get:
      tags:
        - postSecondarySchool
      summary: Count instances of the model matched by where from the data source.
      operationId: postSecondarySchool.count
      parameters:
        - name: where
          in: query
          description: Criteria to match model instances
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              count:
                type: number
                format: double
      deprecated: false
  /postSecondarySchools/change-stream:
    post:
      tags:
        - postSecondarySchool
      summary: Create a change stream.
      operationId: postSecondarySchool.createChangeStream__post_postSecondarySchools_change-stream
      parameters:
        - name: options
          in: formData
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: file
      deprecated: false
    get:
      tags:
        - postSecondarySchool
      summary: Create a change stream.
      operationId: postSecondarySchool.createChangeStream__get_postSecondarySchools_change-stream
      parameters:
        - name: options
          in: query
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: file
      deprecated: false
  /transcriptSubmissions:
    post:
      tags:
        - transcriptSubmission
      summary: Create a new instance of the model and persist it into the data source.
      operationId: transcriptSubmission.create
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            $ref: '#/definitions/transcriptSubmission'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/transcriptSubmission'
      deprecated: false
    put:
      tags:
        - transcriptSubmission
      summary: Update an existing model instance or insert a new one into the data source.
      operationId: transcriptSubmission.upsert
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            $ref: '#/definitions/transcriptSubmission'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/transcriptSubmission'
      deprecated: false
    get:
      tags:
        - transcriptSubmission
      summary: Find all instances of the model matched by filter from the data source.
      operationId: transcriptSubmission.find
      parameters:
        - name: filter
          in: query
          description: 'Filter defining fields, where, include, order, offset, and limit'
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: array
            items:
              $ref: '#/definitions/transcriptSubmission'
      deprecated: false
  '/transcriptSubmissions/{id}/exists':
    get:
      tags:
        - transcriptSubmission
      summary: Check whether a model instance exists in the data source.
      operationId: 'transcriptSubmission.exists__get_transcriptSubmissions_{id}_exists'
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              exists:
                type: boolean
      deprecated: false
  '/transcriptSubmissions/{id}':
    head:
      tags:
        - transcriptSubmission
      summary: Check whether a model instance exists in the data source.
      operationId: 'transcriptSubmission.exists__head_transcriptSubmissions_{id}'
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              exists:
                type: boolean
      deprecated: false
    get:
      tags:
        - transcriptSubmission
      summary: Find a model instance by id from the data source.
      operationId: transcriptSubmission.findById
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
        - name: filter
          in: query
          description: Filter defining fields and include
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/transcriptSubmission'
      deprecated: false
    delete:
      tags:
        - transcriptSubmission
      summary: Delete a model instance by id from the data source.
      operationId: transcriptSubmission.deleteById
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
      deprecated: false
    put:
      tags:
        - transcriptSubmission
      summary: Update attributes for a model instance and persist it into the data source.
      operationId: transcriptSubmission.prototype.updateAttributes
      parameters:
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            $ref: '#/definitions/transcriptSubmission'
        - name: id
          in: path
          description: PersistedModel id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/transcriptSubmission'
      deprecated: false
  /transcriptSubmissions/findOne:
    get:
      tags:
        - transcriptSubmission
      summary: Find first instance of the model matched by filter from the data source.
      operationId: transcriptSubmission.findOne
      parameters:
        - name: filter
          in: query
          description: 'Filter defining fields, where, include, order, offset, and limit'
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/transcriptSubmission'
      deprecated: false
  /transcriptSubmissions/update:
    post:
      tags:
        - transcriptSubmission
      summary: Update instances of the model matched by where from the data source.
      operationId: transcriptSubmission.updateAll
      parameters:
        - name: where
          in: query
          description: Criteria to match model instances
          required: false
          type: string
          format: JSON
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            $ref: '#/definitions/transcriptSubmission'
      responses:
        '200':
          description: Request was successful
          schema:
            description: The number of instances updated
            type: object
      deprecated: false
  /transcriptSubmissions/count:
    get:
      tags:
        - transcriptSubmission
      summary: Count instances of the model matched by where from the data source.
      operationId: transcriptSubmission.count
      parameters:
        - name: where
          in: query
          description: Criteria to match model instances
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              count:
                type: number
                format: double
      deprecated: false
  /transcriptSubmissions/change-stream:
    post:
      tags:
        - transcriptSubmission
      summary: Create a change stream.
      operationId: transcriptSubmission.createChangeStream__post_transcriptSubmissions_change-stream
      parameters:
        - name: options
          in: formData
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: file
      deprecated: false
    get:
      tags:
        - transcriptSubmission
      summary: Create a change stream.
      operationId: transcriptSubmission.createChangeStream__get_transcriptSubmissions_change-stream
      parameters:
        - name: options
          in: query
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: file
      deprecated: false
definitions:
  postSecondarySchool:
    properties:
      name:
        type: string
      id:
        type: number
        format: double
    required:
      - name
    additionalProperties: false
  x-any:
    properties: {}
  transcriptSubmission:
    properties:
      schoolID:
        type: number
        format: double
      submissionDate:
        type: string
        format: date
      userID:
        type: string
      id:
        type: number
        format: double
    required:
      - schoolID
      - submissionDate
      - userID
    additionalProperties: false
swagger: '2.0'
info:
  x-ibm-name: transcript
  version: 1.0.0
  title: transcript
schemes:
  - https
host: $(catalog.host)
basePath: /api
consumes:
  - application/json
produces:
  - application/json
securityDefinitions: {}
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  catalogs:
    apic-dev:
      properties:
        runtime-url: $(TARGET_URL)
    sb:
      properties:
        runtime-url: 'http://localhost:4001'
  assembly:
    execute:
      - invoke:
          target-url: $(runtime-url)$(request.path)$(request.search)
